config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root  'pages#main', as: 'home'
  get '/index', to: 'pages#main'
  
  #routes related to login and sign up
  get   '/login',   to: 'sessions#login', as: 'login'
  get 'auth/:provider/callback', to: 'sessions#create_auth'
  post  '/login',   to: 'sessions#create'
  delete    '/logout',  to: 'sessions#destroy'

  
  get    '/signup',  to: 'accounts#new'
  post    '/signup',  to: 'accounts#create'
  
  get 'auth/failure', to:redirect('/login')
  get   '/temp',     to: 'pages#temp'
  get '/borrow',    to: 'itens#borrow'
  
	get '/sidebar_intialize' => 'accounts#userSidebar_Info'
	get '/userdashboard_initialize' => 'accounts#userDashboard_Info'

	# Routes to handlers related to search-result page
	get '/result' => 'itens#showResult'
	get '/result_api' => 'itens#generateResult'	

  resources:profiles
  resources:public_profiles
  resources:pays
  
  get '/pays/:id/editTwo', to: 'pays#editTwo', as: :pay_editTwo
  
  
	# Routes to dashboards
	get '/user' => 'dashboards#user'
	#get '/admin' => 'dashboards#admin'

	get '/admin_reports' => 'dashboard#show_report'
  
  get '/resendConfirmation', to:'accounts#resendConfirmation'
  
  resources:accounts do
      post :resendConfirmation, :on => :collection
      member do
          get :confirm_email
      end
  end
  
  resources :password_resets,     only: [:new, :create, :edit, :update]
  
  resources:categories

  get '/category/departments' => 'categories#departments'
  get '/category/department/category_names' => 'categories#by_department'
  get '/category/id' => 'categories#find_id'
  resources:itens
  
	# Routes related to request manipulation, request history and relevant api
	get '/request_borrowed' => 'request#page_borrowed'
	get '/request_lended' => 'request#page_lended'
    get '/request' => 'request#show'
    get '/request/new/:id' => 'request#complete'
	post '/request' => 'request#create'
	put '/request' => 'request#update'

	# Routes related to feedback manipulation and relevant api
	post '/feedback/to-borrower' => 'feedback#create_toBorrower'
	post '/feedback/to-lender' => 'feedback#create_toLender'
	get '/feedback' => 'feedback#show'
    
  # Routes related to items in user dashboard
  get '/user_item' => 'user_items#show_all'
  get '/user_item_all' => 'user_items#get_data_all'

  get '/user_item/:id' => 'user_items#show' 
  get '/user_item/info/:id' => 'user_items#get_data'

  put '/user_item' => 'user_items#destroy'

  get '/user_items/new' => 'user_items#new'
  # route for creating new item
	post '/user_item' => 'user_items#create'

  get '/user_item/edit/:id' => 'user_items#edit'
  put '/user_item/edit' => 'user_items#update'
  get '/address' => 'user_items#get_address'
  post '/address_new' => 'user_items#add_address'
  get '/get_borrower' => 'user_items#find_borrower'

	# Routes for redirecting to system pages (error handler)
	get '/404' => 'application#page_not_found'
    
	# Routes for searching (public access granted)
	get '/search/keyword_prompt' => 'itens#keyword_prompt'
	#get '/search/geo/:lon/:lat'
    
    #routes related to public item show page
    get '/search_show', to: 'itens#search_show', as: 'search_show'
    
    #Routes for testing purposes
      get   '/temp',     to: 'pages#temp'
      get   '/termsOfService', to:'pages#termsOfService'
      get   '/privacyPolicy', to:'pages#privacy'
      get   '/contactUs', to:'pages#contactus'
      get   '/aboutUs',  to:'pages#about'
      get   '/FAQ',  to:'pages#FAQ'
      get   '/team',  to:'pages#team'
      get '/Error' => 'pages#error'

      get '/sitemap' => 'sitemap#sitemap'

  get '/userflow' => 'pages#userflow'
  
  
      # For file transfer
  post '/media_contents' => 'media_contents#create'
  get '/media_contents' => 'media_contents#find_url'

	get '/report' => 'reports#index'
	post '/report' => 'reports#create'

  get '/unavailable_time' => 'itens#unavailable_time'

end

app/models/iten.rb
class Iten < ApplicationRecord
validates :owner, :condition, :time_start, :time_end, :name, :presence => true
end

app/controllers/itens_controller.rb
class ItensController < ApplicationController
    def new
    end
    def edit
    end
    def create
    end
    def update
    end
    
    def show
        @item = Iten.find(params[:id])
    end
    
    def index
        @item_ids = []
        @categories = Category.where(:department => params[:department])
        @categories.each do |cat|
            puts cat.id
            @item_ids << Iten.where(:category_id => cat.id).map(&:id)
        end
        

    end
    
    def destroy
        @item = Itens.find(params[])
        @item.update(params.require(:item).permit(:status))
	end
	
	def keyword_prompt
		#search_result = ActiveRecord::Base.connection.exec_query("SELECT name FROM Itens WHERE name LIKE '"+params[:input]+"%' ")
		search_result = Iten.where("name like ?", params[:input]+"%")
		render :json => {:status => 200, :result => search_result}
	end

	def showResult
	end

	def generateResult
		keyword = params[:keyword]
		city = "Toronto"
		province = "Ontario"
		country = "Canada"
		if(params[:city] != "undefined" && params[:province] != "undefined" && params[:country] != "undefined")
			city = params[:city]
			province = params[:province]
			country = params[:country]
		end

		
		# Consider about two cases
		# Case 1: Keyword of Itens (id, name, brand, 10-digit or 13-digit isbn)
		# Case 2: Keyword of Users (display_name, email)
		# Case 3: Keyword of Locations (current_city)

		############################ User Check ##################################
		# Situation 1: Email
		# Situation 2: Display_name
		email_check = (keyword =~ /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/)
		user_avatar = nil
		if(email_check == 0)
			search_byUserEmail = ActiveRecord::Base.connection.exec_query("SELECT Accounts.id, display_name, gender, language, country, avatar_url FROM Accounts, Profiles WHERE Accounts.email = Profiles.email AND Profiles.email = '"+keyword+"';")
			search_byUserEmail_borrowRate = ActiveRecord::Base.connection.exec_query("SELECT AVG(feedback_to_borrowers.rate) AS \"borrow_rate\" FROM feedback_to_borrowers, requests WHERE requests.borrower = '"+keyword+"' AND feedback_to_borrowers.request_id = requests.id;")
			search_byUserEmail_lendRate = ActiveRecord::Base.connection.exec_query("SELECT AVG(feedback_to_lenders.rate) AS \"lend_rate\" FROM feedback_to_lenders, requests, items WHERE items.owner = '"+keyword+"' AND feedback_to_lenders.request_id = requests.id AND requests.item_id = items.id;")
			@profile = Profile.find_by_email(keyword)
			if(@profile)
				user_avatar = url_for(@profile.avatar)
			end
		end
		#search_byUserName = ActiveRecord::Base.connection.exec_query("SELECT email, display_name, gender, language, country, avatar_url FROM Profiles WHERE display_name = '"+keyword+"';")
		############################ Itens Check ##################################
		# Situation 1: ISBN
		if(keyword.to_i.to_s == keyword && (keyword.length==13 || keyword.length==10))
			search_byISBN = ActiveRecord::Base.connection.exec_query("SELECT Pickupaddresses.postal_code AS \"postcode\", Profiles.avatar_url AS \"ownerPhoto\", Itens.condition AS \"itemCondition\", Itens.id AS \"itemID\", Itens.name, Itens.rate_level AS \"minRate\", Itens.photo_url AS \"itemPhoto\", Profiles.display_name AS \"ownerName\", Accounts.id AS \"ownerID\" FROM Itens, Profiles, Accounts, Pickupaddresses WHERE Itens.address = Pickupaddresses.id AND Pickupaddresses.city = '"+city+"' AND Pickupaddresses.province = '"+province+"' AND Pickupaddresses.country = '"+country+"' AND Accounts.email = Profiles.email AND Itens.owner = Profiles.email AND Itens.isbn = '"+keyword.to_i+"';")
			search_byISBN_history = ActiveRecord::Base.connection.exec_query("SELECT Itens.id AS \"itemID\", COUNT(*) AS \"count\" FROM Requests, Itens, Pickupaddresses WHERE Itens.address = Pickupaddresses.id AND Pickupaddresses.city = '"+city+"' AND Pickupaddresses.province = '"+province+"' AND Pickupaddresses.country = '"+country+"' AND Requests.item_id = Itens.id AND Itens.isbn = '"+keyword.to_i+"' GROUP BY Itens.id;")
			search_byISBN_lenderEmail = ActiveRecord::Base.connection.exec_query("SELECT Profiles.email, Accounts.id FROM Itens, Profiles, Accounts, Pickupaddresses WHERE Itens.address = Pickupaddresses.id AND Pickupaddresses.city = '"+city+"' AND Pickupaddresses.province = '"+province+"' AND Pickupaddresses.country = '"+country+"' AND Accounts.email = Profiles.email AND Itens.owner = Profiles.email AND Itens.isbn = '"+keyword.to_i+"';")
			search_byISBN_lenderAvatar = Hash.new
			search_byISBN_lenderAVG = Hash.new
			search_byISBN_lenderEmail.each { |x|
				search_byISBN_lenderAvatar[x["id"]] = url_for(Profile.find_by_email(x["email"]).avatar)
				temp = ActiveRecord::Base.connection.exec_query("SELECT Itens.owner, AVG(Feedback_to_lenders.rate) AS \"average\" FROM Feedback_to_lenders, Requests, Itens WHERE Feedback_to_lenders.request_id = Requests.id AND Requests.item_id = Itens.id AND Itens.owner = '"+x["email"]+"';")
				
				if(temp.length > 0)
					search_byISBN_lenderAVG[x["id"]] = temp[0]["average"]
				else
					search_byISBN_lenderAVG[x["id"]] = "-"
				end
			}
		end

		# Situation 2: Id (Abandoned)
		#if(keyword.to_i.to_s == keyword)
		#	search_byItenID = ActiveRecord::Base.connection.exec_query("SELECT Profiles.avatar_url AS ownerPhoto, Itens.condition AS itemCondition, Itens.id AS itemID, Itens.name, Itens.rate_level AS minRate, Itens.photo_url AS itemPhoto, Profiles.display_name AS ownerName, Accounts.id AS ownerID FROM Itens, Profiles, Accounts WHERE Accounts.email = Profiles.email AND Itens.owner = Profiles.email AND Itens.id = "+keyword.to_i+";")
		#end

		# Situation 3: Name & Brand
		search_byItemNameAndBrand = ActiveRecord::Base.connection.exec_query("SELECT Pickupaddresses.postal_code AS \"postcode\", Profiles.email, Profiles.avatar_url AS \"ownerPhoto\", Itens.condition AS \"itemCondition\", Itens.id AS \"itemID\", Itens.name, Itens.rate_level AS \"minRate\", Itens.photo_url AS \"itemPhoto\", Profiles.display_name AS \"ownerName\", Accounts.id AS \"ownerID\" FROM Itens, Profiles, Accounts, Pickupaddresses WHERE Itens.address = Pickupaddresses.id AND Pickupaddresses.city = '"+city+"' AND Pickupaddresses.province = '"+province+"' AND Pickupaddresses.country = '"+country+"' AND Accounts.email = Profiles.email AND Itens.owner = Profiles.email AND (LOWER(Itens.name) LIKE LOWER('%"+keyword+"%') OR LOWER(Itens.brand) = LOWER('%"+keyword+"%'));")
		search_byItemNameAndBrand_history = ActiveRecord::Base.connection.exec_query("SELECT Itens.id AS \"itemID\", COUNT(*) AS \"count\" FROM Requests, Itens, Pickupaddresses WHERE Itens.address = Pickupaddresses.id AND Pickupaddresses.city = '"+city+"' AND Pickupaddresses.province = '"+province+"' AND Pickupaddresses.country = '"+country+"' AND Requests.item_id = Itens.id AND (LOWER(Itens.name) LIKE LOWER('%"+keyword+"%') OR LOWER(Itens.brand) = LOWER('%"+keyword+"%')) GROUP BY Itens.id;")
		search_byItemNameAndBrand_lenderEmail = ActiveRecord::Base.connection.exec_query("SELECT Profiles.email, Accounts.id FROM Itens, Profiles, Accounts, Pickupaddresses WHERE Itens.address = Pickupaddresses.id AND Pickupaddresses.city = '"+city+"' AND Pickupaddresses.province = '"+province+"' AND Pickupaddresses.country = '"+country+"' AND Accounts.email = Profiles.email AND Itens.owner = Profiles.email AND (LOWER(Itens.name) LIKE LOWER('%"+keyword+"%') OR LOWER(Itens.brand) = LOWER('%"+keyword+"%'));")
		search_byItemNameAndBrand_lenderAvatar = Hash.new
		search_byItemNameAndBrand_lenderAVG = Hash.new
		search_byItemNameAndBrand_lenderEmail.each { |x|
			search_byItemNameAndBrand_lenderAvatar[x["id"]] = url_for(Profile.find_by_email(x["email"]).avatar)
			temp = ActiveRecord::Base.connection.exec_query("SELECT Itens.owner, AVG(Feedback_to_lenders.rate) AS \"average\" FROM Feedback_to_lenders, Requests, Itens WHERE Feedback_to_lenders.request_id = Requests.id AND Requests.item_id = Itens.id AND Itens.owner = '"+x["email"]+"' GROUP BY Itens.owner;")
			if(temp.length>0)
				search_byItemNameAndBrand_lenderAVG[x["id"]] = temp[0]["average"]
			else
				search_byItemNameAndBrand_lenderAVG[x["id"]] = "-"
			end
				

		}
		
		if(:search_byItemNameAndBrand.size==0)
			require 'gingerice'
			parser = Gingerice::Parser.new
			correction = parser.parse(keyword)
			correction_result = correction["result"].downcase
			search_byCorrection = ActiveRecord::Base.connection.exec_query("SELECT Pickupaddresses.postal_code AS \"postcode\", Profiles.avatar_url AS \"ownerPhoto\", Itens.condition AS \"itemCondition\", Itens.id AS \"itemID\", Itens.name, Itens.rate_level AS \"minRate\", Itens.photo_url AS \"itemPhoto\", Profiles.display_name AS \"ownerName\", Accounts.id AS \"ownerID\" FROM Itens, Profiles, Accounts, Pickupaddresses WHERE Itens.address = Pickupaddresses.id AND Pickupaddresses.city = '"+city+"' AND Pickupaddresses.province = '"+province+"' AND Pickupaddresses.country = '"+country+"' AND Accounts.email = Profiles.email AND Itens.owner = Profiles.email AND (LOWER(Itens.name) LIKE LOWER('%"+correction_result+"%') OR LOWER(Itens.brand) = LOWER('%"+correction_result+"%'));")
			search_byCorrection_history = ActiveRecord::Base.connection.exec_query("SELECT Itens.id AS \"itemID\", COUNT(*) AS \"count\" FROM Requests, Itens, Pickupaddresses WHERE Itens.address = Pickupaddresses.id AND Pickupaddresses.city = '"+city+"' AND Pickupaddresses.province = '"+province+"' AND Pickupaddresses.country = '"+country+"' AND Requests.item_id = Itens.id AND (LOWER(Itens.name) LIKE LOWER('%"+correction_result+"%') OR LOWER(Itens.brand) = LOWER('%"+correction_result+"%')) GROUP BY Itens.id;")

app/helpers/itens_helper.rb
module ItensHelper
end

app/views/itens/index.html.erb
<!doctype html>
<html class="no-js" lang="zxx">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Exporso - Product Details Sidebar</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Favicon -->
    <link rel="shortcut icon" type="image/x-icon" href="assets/img/favicon.png">

    <!-- all css here -->
    <%= stylesheet_link_tag 'bundle.css' %>
    <%= stylesheet_link_tag 'style.css' %>

    <script src="assets/js/vendor/modernizr-2.8.3.min.js"></script>
</head>

<!-- all custom css here -->
<style type="text/css">
    .column-text-light{
    font-size: 14px !important;
    color: #f4f4f4 !important;
    font-weight: 100 !important;
    }
    .column-text-dark{
    font-size: 14px !important;
    font-weight: 100 !important;
    margin-left:3em !important;
    }

</style>

<body>
    <!-- Add your site or application content here -->
    <div class="exporso_wrapper">
        
        <!--product Details Inner-->
        <div class="product_details_inner left_sidebar ptb-60 border-top">
            
            <%= render 'layouts/department_list' %>
            
            <!--error section start-->
            <div class="container border-bottom">
                <% flash.each do |key, value| %>
                    <div id="error_explanation">
                        <div class="alert alert-danger">
                            <ul><li><%= content_tag :div, value, class: "flash #{key}" %></li> </ul>
                        </div>
                    </div>
                <% end %>
            </div>
            <!--error section end-->
            
            <!--item listing section start-->
            <div class="container ptb-20">
                <div class="row">
                <% @item_ids.each do |item_id_col| %>
                
                    <% item_id_col.each do |item_id|%>
                    <% @item = Iten.find_by(id: item_id)%>
                        <div class="col-lg-4 ptb-20">
                            <div class="card-deck mt-3">
                                <div class="card">
                                    <%= link_to image_tag("#{@item.photo_url}",width: 356, height: 280), iten_path(@item) ,{ :class=>"center_image" }%>
                                    <p class="card-text-center" style="text-align: center;"><%= @item.name %></p>
                                </div>
                            </div>
                        </div>
                    <% end %>
                <% end %>
                </div>
                
            </div>

        </div>

    </div>

</body>
</html>

app/views/itens/show.html.erb
<!doctype html>
<html class="no-js" lang="zxx">
    <head>
        <meta charset="utf-8">
            <meta http-equiv="x-ua-compatible" content="ie=edge">
                <title>Exporso - Product Details Sidebar</title>
                <meta name="description" content="">
                    <meta name="viewport" content="width=device-width, initial-scale=1">
                        <!-- Favicon -->
                        <link rel="shortcut icon" type="image/x-icon" href="assets/img/favicon.png">
                            
                            <!-- all css here -->
                            <%= stylesheet_link_tag 'style.css' %>
                           
                            <%= javascript_tag "window._token = '#{form_authenticity_token}'" %> <%=
                                javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
                            <script src="assets/js/vendor/modernizr-2.8.3.min.js"></script>
                            
                            <!-- Calendar related -->
                            <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />
    </head>
    <style type="text/css">
        .column-text-light{
            font-size: 14px !important;
            color: #f4f4f4 !important;
            font-weight: 100 !important;
        }
        .column-text-dark{
            font-size: 14px !important;
            font-weight: 100 !important;
            margin-left:3em !important;
        }
        .modal-header {
            background-color: rgba(128, 198, 185, 0.89);
            color: white;
        }
        .modal-title {
            font-family: -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol","Noto Color Emoji";
            font-weight: 200
        }

    </style>
    <body>
        <!-- Add your site or application content here -->
        <div class="exporso_wrapper">
            
            <!--product Details Inner-->
            <div class="product_details_inner left_sidebar ptb-60 border-top ">
                <%= render 'layouts/department_list' %>
                
                <div class="container border-bottom">
                    <% flash.each do |key, value| %>
                    <div id="error_explanation">
                        
                        <div class="alert alert-danger">
                            <ul>
                                <li><%= content_tag :div, value, class: "flash #{key}" %></li>
                            </ul>
                        </div>
                        
                    </div>
                    <% end %>

                        <div class="container ptb-20"  style="padding-top:30px">
                            <div class="row">
                                <!--Product Tab Style start-->
                                <div class="col">
                                    <div class="product-details-img-content">
                                        <div class="product-details-tab">
                                            <div id="img-1" class="zoomWrapper single-zoom">
                                                <a href="#">
                                                    <%= image_tag("#{@item.photo_url}",width: 400, height: 400) %>
                                                </a>
                                            </div>
                                            
                                        </div>
                                    </div>
                                </div>
                                <!--Product Tab Style End-->
                                <div class="col">
                                    <div class="product-details-content">
                                        <h3><%= @item.name %></h3>
                                        <div class="rating-number">
                                            <div class="product_rating">
                                                <a href="#"><i class="zmdi zmdi-star"></i></a>
                                                <a href="#"><i class="zmdi zmdi-star"></i></a>
                                                <a href="#"><i class="zmdi zmdi-star"></i></a>
                                                <a href="#"><i class="zmdi zmdi-star"></i></a>
                                                <a href="#"><i class="zmdi zmdi-star-half"></i></a>
                                            </div>
                                            
                                        </div>
                                        <div class="price_amount">
                                            <span class="current_price"><%= "Condition: #{@item.condition}" %></span>
                                            <span class="discount_price">Hot</span>
                                        </div>
                                        
                                        <div class="price_amount">
                                            <span class="current_price"><%= "Available Times:" %></span><br>
                                                <span class="current_price"> <%= "#{@item.time_start} - #{@item.time_end}" %></span>
                                            
                                        </div>
                                        
                                        <br></br>
                                        
                                        <p><%= @item.description %></p>

                                        
                                        <div class="single_product_action d-flex align-items-center">
                                            
                                            <!-- Button to Open the Modal -->
                                            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
                                                Borrow this now!
                                            </button>
                                            
                                            <!-- The Modal -->
                                            <div class="modal" id="myModal">
                                                <div class="modal-dialog">
                                                    <div class="modal-content">
                                                        
                                                        <!-- Modal Header -->
                                                        <div class="modal-header">
                                                            <h4 class="modal-title">Want to borrow this now?</h4>
                                                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                                                        </div>
                                                        
                                                        <!-- Modal body -->
                                                        <div class="modal-body">
                                                            <% if not logged_in? %>
                                                                <p><h6> Are you new to our community? Join us today to become a Neighborrow insider ! </h6>
                                                                <%= link_to "Click here to Sign up", new_account_url %></p>
                                                                <p><h6> Already have an account? </h6>
                                                                <%= link_to "Click here to Login", login_url %></p>

                                                            <% else %>
                                                            
                                                            <div class="row" >
                                                                <div class="col-9" style="background:white;padding-right:100px; padding-top:30px;">
                                                                    <input type="text" name="daterange" style="font-size:15px" id='date-input'/>
                                                                </div>
                                                            </div>
                                                            
                                                            <div>
                                                                <input type="submit" value="Request to borrow now!" onclick='btnRequest()'/>
                                                            </div>
                                                            <% end %>
    
                                                        </div>
                                                        
                                                        <!-- Modal footer -->
                                                        <div class="modal-footer">
                                                            <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                                                        </div>
                                                        
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <br></br>
                                        <div class="product-share">
                                            <div class="share_label">
                                                <span>Posted by :</span>
                                                <% @owner = Account.find_by(email: @item.owner) %>
                                                <% @ownerProfile = Profile.find_by(email: @item.owner) %>
                                                <%= link_to "#{@ownerProfile.display_name}", controller: "public_profiles", action: "show", id:@owner.id %>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            
            <!--Google API section Start -->
            <div class="newsletter_section ptb-80 " style="padding-top:30px">
                <iframe src="https://www.google.com/maps/embed/v1/place?key=AIzaSyAnpp7FDgcbpfqNskhkAR_Y2E_uMitVXd0
                    &q=place_id:ChIJ-bt_oLg0K4gRNNZIQRz78JA" width="100%" height="550" frameborder="0" style="border:0" allowfullscreen>
                </iframe>
            </div>
            <!--Newsletter section end -->
            
            </footer>
            <!--Footer end-->
            
            
            
        </div>
        
        
        
        <!-- all js here -->
        
        <!-- Calendar related -->
        <script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>
        <script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
        <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>

        <script src="/assets/js/item_show.js"></script>
        
        <script>
            $(function() {
              $('input[name="daterange"]').daterangepicker({
                                                           opens: 'left'
                                                           }, function(start, end, label) {
                                                           console.log("A new date selection was made: " + start.format('YYYY-MM-DD') + ' to ' + end.format('YYYY-MM-DD'));
                                                           });
              });
            </script>

        
    </body>
</html>