config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root  'pages#main', as: 'home'
  get '/index', to: 'pages#main'
  
  #routes related to login and sign up
  get   '/login',   to: 'sessions#login', as: 'login'
  get 'auth/:provider/callback', to: 'sessions#create_auth'
  post  '/login',   to: 'sessions#create'
  delete    '/logout',  to: 'sessions#destroy'

  
  get    '/signup',  to: 'accounts#new'
  post    '/signup',  to: 'accounts#create'
  
  get 'auth/failure', to:redirect('/login')
  get   '/temp',     to: 'pages#temp'
  get '/borrow',    to: 'itens#borrow'
  
	get '/sidebar_intialize' => 'accounts#userSidebar_Info'
	get '/userdashboard_initialize' => 'accounts#userDashboard_Info'

	# Routes to handlers related to search-result page
	get '/result' => 'itens#showResult'
	get '/result_api' => 'itens#generateResult'	

  resources:profiles
  resources:public_profiles
  resources:pays
  
  get '/pays/:id/editTwo', to: 'pays#editTwo', as: :pay_editTwo
  
  
	# Routes to dashboards
	get '/user' => 'dashboards#user'
	#get '/admin' => 'dashboards#admin'

	get '/admin_reports' => 'dashboard#show_report'
  
  get '/resendConfirmation', to:'accounts#resendConfirmation'
  
  resources:accounts do
      post :resendConfirmation, :on => :collection
      member do
          get :confirm_email
      end
  end
  
  resources :password_resets,     only: [:new, :create, :edit, :update]
  
  resources:categories

  get '/category/departments' => 'categories#departments'
  get '/category/department/category_names' => 'categories#by_department'
  get '/category/id' => 'categories#find_id'
  resources:itens
  
	# Routes related to request manipulation, request history and relevant api
	get '/request_borrowed' => 'request#page_borrowed'
	get '/request_lended' => 'request#page_lended'
    get '/request' => 'request#show'
    get '/request/new/:id' => 'request#complete'
	post '/request' => 'request#create'
	put '/request' => 'request#update'

	# Routes related to feedback manipulation and relevant api
	post '/feedback/to-borrower' => 'feedback#create_toBorrower'
	post '/feedback/to-lender' => 'feedback#create_toLender'
	get '/feedback' => 'feedback#show'
    
  # Routes related to items in user dashboard
  get '/user_item' => 'user_items#show_all'
  get '/user_item_all' => 'user_items#get_data_all'

  get '/user_item/:id' => 'user_items#show' 
  get '/user_item/info/:id' => 'user_items#get_data'

  put '/user_item' => 'user_items#destroy'

  get '/user_items/new' => 'user_items#new'
  # route for creating new item
	post '/user_item' => 'user_items#create'

  get '/user_item/edit/:id' => 'user_items#edit'
  put '/user_item/edit' => 'user_items#update'
  get '/address' => 'user_items#get_address'
  post '/address_new' => 'user_items#add_address'
  get '/get_borrower' => 'user_items#find_borrower'

	# Routes for redirecting to system pages (error handler)
	get '/404' => 'application#page_not_found'
    
	# Routes for searching (public access granted)
	get '/search/keyword_prompt' => 'itens#keyword_prompt'
	#get '/search/geo/:lon/:lat'
    
    #routes related to public item show page
    get '/search_show', to: 'itens#search_show', as: 'search_show'
    
    #Routes for testing purposes
      get   '/temp',     to: 'pages#temp'
      get   '/termsOfService', to:'pages#termsOfService'
      get   '/privacyPolicy', to:'pages#privacy'
      get   '/contactUs', to:'pages#contactus'
      get   '/aboutUs',  to:'pages#about'
      get   '/FAQ',  to:'pages#FAQ'
      get   '/team',  to:'pages#team'
      get '/Error' => 'pages#error'

      get '/sitemap' => 'sitemap#sitemap'

  get '/userflow' => 'pages#userflow'
  
  
      # For file transfer
  post '/media_contents' => 'media_contents#create'
  get '/media_contents' => 'media_contents#find_url'

	get '/report' => 'reports#index'
	post '/report' => 'reports#create'

  get '/unavailable_time' => 'itens#unavailable_time'

end

app/models/pay.rb
class Pay < ApplicationRecord
  
  serialize :notification_params, Hash
  def paypal_url(return_path)
      values = {
          business: "sixneighborrow-facilitator@gmail.com",
          cmd: "_xclick",
          upload: 1,
          return: "https://neighborrow.herokuapp.com#{return_path}",
          amount: self.add_credit,
          item_name: "Neighborrow Credit",
      }
      "https://www.sandbox.paypal.com/cgi-bin/webscr?" + values.to_query
  end
  
  def payout_url(return_path)
      values = {
          :sender_batch_header => {
              :sender_batch_id => SecureRandom.hex(8),
              :email_subject => 'You have a Payout!',
          },
          :items => [
          {
              :recipient_type => 'EMAIL',
              amount: self.withdraw_credit,
              :receiver => 'shirt-supplier-one@mail.com',
          }
          ]
      }
      "https://www.sandbox.paypal.com/cgi-bin/webscr?" + values.to_query
  end

end

app/controllers/pays_controller.rb
require 'paypal-sdk-rest'
include PayPal::SDK::REST
include PayPal::SDK::Core::Logging

class PaysController < ApplicationController
	layout false
    def new
        @pay = Pay.new
    end
    
    def create
        @pay = Pay.new(pay_params)
        @pay.save
    end
    
    def show
        @account = Account.find(current_user.id)
        @pay = Pay.find_by_email(@account.email)

        params.permit!
        paymentId = params[:paymentId]
        payerId =params[:PayerID]
        
        if @pay.add && paymentId
            if @pay.payid
                # Get payment ID from query string following redirect
                payment = Payment.find(paymentId)
                # Execute payment with the payer ID from query string following redirect
                if payment.execute(:payer_id => payerId)  #return true or false
                    flash.now[:success] = 'Credit Update Seccuessful'
                    logger.info "Payment[#{payment.id}] executed successfully"
                    params = Hash.new
                    params[:credit] = @pay.credit.to_i + @pay.add_credit.to_i
                    params[:add_credit] = nil
                    params[:payid] = nil
                    params[:add] = false
                    @pay.update(params)
                    else
                    logger.error payment.error.inspect
                end
            end
        end
       
    end
    
   
    
    def edit
        @account = Account.find(current_user.id)
        @pay = Pay.find_by_email(@account[:email])
    end
    
    def editTwo
        @account = Account.find(current_user.id)
        @pay = Pay.find_by_email(@account[:email])
    end
    
    def update
        @account = Account.find(current_user.id)
        @pay = Pay.find_by_email(@account.email)
        
        @pay.update(pay_params)
        
        if @pay.add_credit
            # Build Payment object
            @payment = Payment.new({
                                   :intent =>  "sale",
                                   
                                   # ###Payer
                                   # A resource representing a Payer that funds a payment
                                   # Payment Method as 'paypal'
                                   :payer =>  {
                                   :payment_method =>  "paypal" },
                                   
                                   # ###Redirect URLs
                                   :redirect_urls => {
                                   :return_url => "https://neighborrow.herokuapp.com#{pay_path(@pay)}",
                                   :cancel_url => "https://neighborrow.herokuapp.com/Error" },
                                   
                                   # ###Transaction
                                   # A transaction defines the contract of a
                                   # payment - what is the payment for and who
                                   # is fulfilling it.
                                   :transactions =>  [{
                                   
                                   # ### Payee
                                   # Specify a payee with that user's email or merchant id
                                   # Merchant Id can be found at https://www.paypal.com/businessprofile/settings/
                                   :payee => {
                                   :email => "sixneighborrow-facilitator@gmail.com"
                                   },
                                   
                                   # Iten List
                                   :item_list => {
                                   :items => [{
                                   :name => "item",
                                   :sku => "item",
                                   :price => @pay.add_credit,
                                   :currency => "CAD",
                                   :quantity => 1 }]},
                                   
                                   # ###Amount
                                   # Let's you specify a payment amount.
                                   :amount =>  {
                                   :total => @pay.add_credit,
                                   :currency =>  "CAD" },
                                   :description =>  "This is the payment transaction description." }]})
                                   
                                   # Create Payment and return status
                                   if @payment.create
                                       # Redirect the user to given approval url
                                       @redirect_url = @payment.links.find{|v| v.rel == "approval_url" }.href
                                       params = Hash.new
                                       params[:payid] = @payment.id
                                       params[:add] = true
                                       @pay.update(params)
                                       redirect_to @redirect_url
                                   end
                                   
        elsif @pay.withdraw_credit
            if @pay.withdraw_credit > @pay.credit
                flash.now[:danger] = 'You cannot withdraw more amount than your current credit'
                render  'editTwo'
            else
                if @pay.update(pay_params)
                    params = Hash.new
                    params[:credit] = @pay.credit.to_i - @pay.withdraw_credit.to_i
                    params[:withdraw_credit] = nil
                    @pay.update(params)
                    flash.now[:success] = 'You have successfully submitted the request to withdraw your credit. Please allow 3-5 business days for us to process this transaction.'
                    render 'show'
                else
                    render 'editTwo'
                end
            end
        else
            render '/Error'
        end
        
    end
    
    private def pay_params
        params.require(:pay).permit(:email, :add_credit, :credit, :withdraw_credit)
    end
end

app/helpers/pays_helper.rb
module PaysHelper
end

app/views/pays/edit.html.erb
<!--
* This modified template file is referenced to coreui.io,
* along with other third-party stylesheets and javascript files.
* Source Repository: https://github.com/coreui/coreui-free-bootstrap-admin-template
-->

<!--
* CoreUI - Free Bootstrap Admin Template
* @version v2.1.7
* @link https://coreui.io
* Copyright (c) 2018 creativeLabs ukasz Holeczek
* Licensed under MIT (https://coreui.io/license)
-->

<!DOCTYPE html>
<html lang="en">
<head>
<!-- Meta information used for SEO -->
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
<meta name="description" content="Neighborrow - Your Platform to Borrow and Lend">
<meta name="author" content="Neighborrow">
<meta name="keyword" content="Borrow, Lend, CSC444">
<%= csrf_meta_tags %>
<%= javascript_tag "window._token = '#{form_authenticity_token}'" %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<title>Neighborrow - Blank</title>

<!-- CSS files for third-party icons-->
<link href="/vendors/@coreui/icons/css/coreui-icons.min.css" rel="stylesheet">
<link href="/vendors/flag-icon-css/css/flag-icon.min.css" rel="stylesheet">
<link href="/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
<link href="/vendors/simple-line-icons/css/simple-line-icons.css" rel="stylesheet">

<!-- Base stylesheets & third-party stylesheets-->
<link href="/vendors/@coreui/coreui/css/style.css" rel="stylesheet">
<link href="/vendors/pace-progress/css/pace.min.css" rel="stylesheet">

<!-- Customized stylesheet goes here-->

</head>


<% if logged_in_as_user? (@account.id) %>
<body class="app sidebar-fixed aside-menu-fixed sidebar-md-show" data-turbolinks="false">
<!-- <header class="app-header navbar" style="width:100%" id="headerModule">

</header> -->


<div class="app-body">
<div class="sidebar" id="menuModule"></div>

<main class="main">
<span id="subHeaderModule"></span>

<div class="container-fluid">
<!-- Main section - Codes for main functionalities in this block -->
<h2>Settings</h2>
<hr>

<div class="row">
<div class="col-lg-12">
<div class="card">
<div class="card-header">
<strong class="text-muted">Top Up Your Credit</strong>
</div>
<div class="card-body">

<%= form_for @pay, url:pay_path do |f| %>

<div class="form-group">
<label>Your Current Credit:</label>
<%= @pay.credit %>
</div>


<div class="form-group">
<label>Enter the amount of credits you want to top up below (1 dollar = 1 credit):</label>
<%= f.text_field :add_credit, class: 'form-control', required: 'required' %>
</div>



<%= f.submit class: "btn btn--form", class: "btn btn-primary pull-right"%>
<% end %>
</div>
</div>
</div>
<!-- /.col-->
</div>
<!-- /.row-->

</div>

</main>

</div>
<% else %>
<div class = "app flex-row align-items-center">

<!-- <div class="row"> -->
<div class="container">
<div class="row justify-content-center">
<div class="col-md-6">
<div class="clearfix">
<h1 class="float-left display-3 mr-4">403</h1>
<h4 class="pt-3">Oops! Forbidden Page</h4>
<p class="text-muted">
Looks like you don't have permission to access this page.
You might be accessing an account that's not yours
</p>
</div>
</div>
</div>
</div>

<!-- </div> -->
<!-- <div class="row"> -->
<!-- <div class="container">
<div class="row justify-content-center">
<div class="col-md-6">
<div class="clearfix">
<span>
<h5 class="pt-3">To edit your own account's credit, click <%= link_to "HERE", url: edit_pay_path, id: @account.id %> </h5>
</span>
</div>
</div>
</div>

</div> -->

<!-- </div> -->
</div>
<!-- <div class = "app flex-row align-items-center">
<div class="container">
<div class="row justify-content-center">
<div class="col-md-6">
<div class="clearfix">
<span>
<h5 class="pt-3">To edit your own accout's credit, click <%= link_to "HERE", url: edit_pay_path, id: @account.id %> </h5>
</span>
</div>
</div>
</div>

</div>
</div> -->
<!-- <div class = "app flex-row align-items-center">
<div class="row justify-content-center">
<span>
<h5 class="pt-3">To edit your own accout's credit, click <li><%= link_to "HERE", url: edit_pay_path, id: @account.id %></li> </h5>
</span>
</div>
</div> -->

<% end %>


<!-- CoreUI and other third-party plugins (js files) -->
<script src="/vendors/jquery/js/jquery.min.js"></script>
<script src="/vendors/popper.js/js/popper.min.js"></script>
<script src="/vendors/bootstrap/js/bootstrap.min.js"></script>
<script src="/vendors/pace-progress/js/pace.min.js"></script>
<script src="/vendors/perfect-scrollbar/js/perfect-scrollbar.min.js"></script>
<script src="/vendors/@coreui/coreui/js/coreui.min.js"></script>
<script src="/vendors/momentjs/moment.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

<!-- Customized Javascript file goes here -->
<script src="/assets/js/dashboard-init.js?version=1"></script>
<script src="/assets/js/transaction_borrowed.js?version=1"></script>

</body>

</html>

app/views/pays/editTwo.html.erb
<!--
* This modified template file is referenced to coreui.io,
* along with other third-party stylesheets and javascript files.
* Source Repository: https://github.com/coreui/coreui-free-bootstrap-admin-template
-->

<!--
* CoreUI - Free Bootstrap Admin Template
* @version v2.1.7
* @link https://coreui.io
* Copyright (c) 2018 creativeLabs ukasz Holeczek
* Licensed under MIT (https://coreui.io/license)
-->

<!DOCTYPE html>
<html lang="en">
<head>
<!-- Meta information used for SEO -->
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
<meta name="description" content="Neighborrow - Your Platform to Borrow and Lend">
<meta name="author" content="Neighborrow">
<meta name="keyword" content="Borrow, Lend, CSC444">
<%= csrf_meta_tags %>
<%= javascript_tag "window._token = '#{form_authenticity_token}'" %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<title>Neighborrow - Blank</title>

<!-- CSS files for third-party icons-->
<link href="/vendors/@coreui/icons/css/coreui-icons.min.css" rel="stylesheet">
<link href="/vendors/flag-icon-css/css/flag-icon.min.css" rel="stylesheet">
<link href="/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
<link href="/vendors/simple-line-icons/css/simple-line-icons.css" rel="stylesheet">

<!-- Base stylesheets & third-party stylesheets-->
<link href="/vendors/@coreui/coreui/css/style.css" rel="stylesheet">
<link href="/vendors/pace-progress/css/pace.min.css" rel="stylesheet">

<!-- Customized stylesheet goes here-->

</head>


<% if logged_in_as_user? (@account.id) %>
<body class="app sidebar-fixed aside-menu-fixed sidebar-md-show" data-turbolinks="false">
<!-- <header class="app-header navbar" style="width:100%" id="headerModule">

</header> -->


<div class="app-body">
<div class="sidebar" id="menuModule"></div>

<main class="main">
<span id="subHeaderModule"></span>

<div class="container-fluid">
<!-- Main section - Codes for main functionalities in this block -->
<h2>Settings</h2>
<hr>

<div class="row">
<div class="col-lg-12">
<div class="card">
<div class="card-header">
<strong class="text-muted">Top Up Your Credit</strong>
</div>
<div class="card-body">
<% flash.each do |key, value| %>
<div id="error_explanation">
<div class="alert alert-<%= key %>">
<ul>
<li><%= content_tag :div, value, class: "flash #{key}" %></li>
</ul>
</div>
</div>
<% end %>
<%= form_for @pay, url:pay_path do |f| %>

<div class="form-group">
<label>Your Current Credit:</label>
<%= @pay.credit %>
</div>

<div class="form-group">
<label>Currently we only support PayPal. Please enter your PayPal email address to receive the payment:</label>
<%= f.text_field :paypal_email, class: 'form-control', required: 'required', type: 'email'   %>
</div>

<div class="form-group">
<label>Enter the amount of credits you want to withdraw below (1 dollar = 1 credit):</label>
<%= f.text_field :withdraw_credit, class: 'form-control', required: 'required' %>
</div>



<%= f.submit class: "btn btn--form", class: "btn btn-primary pull-right"%>
<% end %>
</div>
</div>
</div>
<!-- /.col-->
</div>
<!-- /.row-->

</div>

</main>

</div>
<% else %>
<div class = "app flex-row align-items-center">

<!-- <div class="row"> -->
<div class="container">
<div class="row justify-content-center">
<div class="col-md-6">
<div class="clearfix">
<h1 class="float-left display-3 mr-4">403</h1>
<h4 class="pt-3">Oops! Forbidden Page</h4>
<p class="text-muted">
Looks like you don't have permission to access this page.
You might be accessing an account that's not yours
</p>
</div>
</div>
</div>
</div>

<!-- </div> -->
<!-- <div class="row"> -->
<!-- <div class="container">
<div class="row justify-content-center">
<div class="col-md-6">
<div class="clearfix">
<span>
<h5 class="pt-3">To edit your own account's credit, click <%= link_to "HERE", url: edit_pay_path, id: @account.id %> </h5>
</span>
</div>
</div>
</div>

</div> -->

<!-- </div> -->
</div>
<!-- <div class = "app flex-row align-items-center">
<div class="container">
<div class="row justify-content-center">
<div class="col-md-6">
<div class="clearfix">
<span>
<h5 class="pt-3">To edit your own accout's credit, click <%= link_to "HERE", url: edit_pay_path, id: @account.id %> </h5>
</span>
</div>
</div>
</div>

</div>
</div> -->
<!-- <div class = "app flex-row align-items-center">
<div class="row justify-content-center">
<span>
<h5 class="pt-3">To edit your own accout's credit, click <li><%= link_to "HERE", url: edit_pay_path, id: @account.id %></li> </h5>
</span>
</div>
</div> -->

<% end %>


<!-- CoreUI and other third-party plugins (js files) -->
<script src="/vendors/jquery/js/jquery.min.js"></script>
<script src="/vendors/popper.js/js/popper.min.js"></script>
<script src="/vendors/bootstrap/js/bootstrap.min.js"></script>
<script src="/vendors/pace-progress/js/pace.min.js"></script>
<script src="/vendors/perfect-scrollbar/js/perfect-scrollbar.min.js"></script>
<script src="/vendors/@coreui/coreui/js/coreui.min.js"></script>
<script src="/vendors/momentjs/moment.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

<!-- Customized Javascript file goes here -->
<script src="/assets/js/dashboard-init.js?version=1"></script>
<script src="/assets/js/transaction_borrowed.js?version=1"></script>

</body>

</html>

app/views/pays/show.html.erb
<!-- 
	* This modified template file is referenced to coreui.io, 
	* along with other third-party stylesheets and javascript files.
	* Source Repository: https://github.com/coreui/coreui-free-bootstrap-admin-template
-->

<!--
* CoreUI - Free Bootstrap Admin Template
* @version v2.1.7
* @link https://coreui.io
* Copyright (c) 2018 creativeLabs 艁ukasz Holeczek
* Licensed under MIT (https://coreui.io/license)
-->

<!DOCTYPE html>
<html lang="en">
<head>
	<!-- Meta information used for SEO -->
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
	<meta name="description" content="Neighborrow - Your Platform to Borrow and Lend">
	<meta name="author" content="Neighborrow">
	<meta name="keyword" content="Borrow, Lend, CSC444">
	<%= csrf_meta_tags %>
	<%= javascript_tag "window._token = '#{form_authenticity_token}'" %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	<title>Neighborrow - Payments</title>

	<!-- CSS files for third-party icons-->
	<link href="/vendors/@coreui/icons/css/coreui-icons.min.css" rel="stylesheet">
	<link href="/vendors/flag-icon-css/css/flag-icon.min.css" rel="stylesheet">
	<link href="/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
	<link href="/vendors/simple-line-icons/css/simple-line-icons.css" rel="stylesheet">

	<!-- Base stylesheets & third-party stylesheets-->
	<link href="/vendors/@coreui/coreui/css/style.css" rel="stylesheet">
	<link href="/vendors/pace-progress/css/pace.min.css" rel="stylesheet">

	<!-- Customized stylesheet goes here-->

</head>


	<% if logged_in_as_user? (@account.id) %>
<body class="app sidebar-fixed aside-menu-fixed sidebar-md-show" data-turbolinks="false">
	<!-- <header class="app-header navbar" style="width:100%" id="headerModule">

	</header> -->
	<header
	class="app-header navbar"
	style="width:100%"
	id="headerModule"
></header>
	
	<div class="app-body">
		<div class="sidebar" id="menuModule"></div>

		<main class="main">
			<span id="subHeaderModule"></span>

			<div class="container-fluid" style="margin-top:20px;">
				<!-- Main section - Codes for main functionalities in this block -->
				<h3>Account Credit</h3>
				<hr>
            
	            <div class="row">
	              <div class="col-lg-12">
	                <div class="card">
	                  <div class="card-header">
	                    <strong class="text-muted">Credit</strong>
	                  </div>
	                    
	                  <div class="card-body">
	                  	<form method="put" class="form-horizontal">
<% flash.each do |key, value| %>
<div id="error_explanation">
<div class="alert alert-<%= key %>">
<ul>
<li><%= content_tag :div, value, class: "flash #{key}" %></li>
</ul>
</div>
</div>
<% end %>
<div class="form-group text-center">
<label>Your Current Credit:</label>
<%= @pay.credit %>
</div>


	                    </form>
	                    

	                    <button class="btn btn-primary btn-block" ><%= link_to "Top Up Your Credit Now", edit_pay_path, method: :get, style: "color: white" %></button>



                        <button class="btn btn-secondary btn-block"><%= link_to "Withdraw Your Credit Now", pay_editTwo_url, method: :get, style: "color: white" %></button>

	                    
	                  </div>
	                </div>
	              </div>
	              <!-- /.col-->
	            </div>
	            <!-- /.row-->	
            
			</div>
			
		</main>
		
	</div>
<% else %>
			<div class = "app flex-row align-items-center">
			
				<!-- <div class="row"> -->
					<div class="container">
				      <div class="row justify-content-center">
				        <div class="col-md-6">
				          <div class="clearfix">
				            <h1 class="float-left display-3 mr-4">403</h1>
				            <h4 class="pt-3">Oops! Forbidden Page</h4>
				            <p class="text-muted">
					            Looks like you don't have permission to access this page.
					            You might be accessing an account's profile that's not yours
				            </p>
				          </div>
				        </div>
				      </div>
				    </div>
			</div>
		<% end %>

		<footer class="app-footer" id="footerModule"></footer>

<!-- CoreUI and other third-party plugins (js files) -->
    <script src="/vendors/jquery/js/jquery.min.js"></script>
    <script src="/vendors/popper.js/js/popper.min.js"></script>
    <script src="/vendors/bootstrap/js/bootstrap.min.js"></script>
    <script src="/vendors/pace-progress/js/pace.min.js"></script>
    <script src="/vendors/perfect-scrollbar/js/perfect-scrollbar.min.js"></script>
    <script src="/vendors/@coreui/coreui/js/coreui.min.js"></script>
		<script src="/vendors/momentjs/moment.js"></script>
		<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    <!-- Customized Javascript file goes here -->
    <script src="/assets/js/dashboard-init.js?version=1"></script>
    <script src="/assets/js/transaction_borrowed.js?version=1"></script>

</body>

</html>