config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root  'pages#main', as: 'home'
  get '/index', to: 'pages#main'
  
  #routes related to login and sign up
  get   '/login',   to: 'sessions#login', as: 'login'
  get 'auth/:provider/callback', to: 'sessions#create_auth'
  post  '/login',   to: 'sessions#create'
  delete    '/logout',  to: 'sessions#destroy'

  
  get    '/signup',  to: 'accounts#new'
  post    '/signup',  to: 'accounts#create'
  
  get 'auth/failure', to:redirect('/login')
  get   '/temp',     to: 'pages#temp'
  get '/borrow',    to: 'itens#borrow'
  
	get '/sidebar_intialize' => 'accounts#userSidebar_Info'
	get '/userdashboard_initialize' => 'accounts#userDashboard_Info'

	# Routes to handlers related to search-result page
	get '/result' => 'itens#showResult'
	get '/result_api' => 'itens#generateResult'	

  resources:profiles
  resources:public_profiles
  resources:pays
  
  get '/pays/:id/editTwo', to: 'pays#editTwo', as: :pay_editTwo
  
  
	# Routes to dashboards
	get '/user' => 'dashboards#user'
	#get '/admin' => 'dashboards#admin'

	get '/admin_reports' => 'dashboard#show_report'
  
  get '/resendConfirmation', to:'accounts#resendConfirmation'
  
  resources:accounts do
      post :resendConfirmation, :on => :collection
      member do
          get :confirm_email
      end
  end
  
  resources :password_resets,     only: [:new, :create, :edit, :update]
  
  resources:categories

  get '/category/departments' => 'categories#departments'
  get '/category/department/category_names' => 'categories#by_department'
  get '/category/id' => 'categories#find_id'
  resources:itens
  
	# Routes related to request manipulation, request history and relevant api
	get '/request_borrowed' => 'request#page_borrowed'
	get '/request_lended' => 'request#page_lended'
    get '/request' => 'request#show'
    get '/request/new/:id' => 'request#complete'
	post '/request' => 'request#create'
	put '/request' => 'request#update'

	# Routes related to feedback manipulation and relevant api
	post '/feedback/to-borrower' => 'feedback#create_toBorrower'
	post '/feedback/to-lender' => 'feedback#create_toLender'
	get '/feedback' => 'feedback#show'
    
  # Routes related to items in user dashboard
  get '/user_item' => 'user_items#show_all'
  get '/user_item_all' => 'user_items#get_data_all'

  get '/user_item/:id' => 'user_items#show' 
  get '/user_item/info/:id' => 'user_items#get_data'

  put '/user_item' => 'user_items#destroy'

  get '/user_items/new' => 'user_items#new'
  # route for creating new item
	post '/user_item' => 'user_items#create'

  get '/user_item/edit/:id' => 'user_items#edit'
  put '/user_item/edit' => 'user_items#update'
  get '/address' => 'user_items#get_address'
  post '/address_new' => 'user_items#add_address'
  get '/get_borrower' => 'user_items#find_borrower'

	# Routes for redirecting to system pages (error handler)
	get '/404' => 'application#page_not_found'
    
	# Routes for searching (public access granted)
	get '/search/keyword_prompt' => 'itens#keyword_prompt'
	#get '/search/geo/:lon/:lat'
    
    #routes related to public item show page
    get '/search_show', to: 'itens#search_show', as: 'search_show'
    
    #Routes for testing purposes
      get   '/temp',     to: 'pages#temp'
      get   '/termsOfService', to:'pages#termsOfService'
      get   '/privacyPolicy', to:'pages#privacy'
      get   '/contactUs', to:'pages#contactus'
      get   '/aboutUs',  to:'pages#about'
      get   '/FAQ',  to:'pages#FAQ'
      get   '/team',  to:'pages#team'
      get '/Error' => 'pages#error'

      get '/sitemap' => 'sitemap#sitemap'

  get '/userflow' => 'pages#userflow'
  
  
      # For file transfer
  post '/media_contents' => 'media_contents#create'
  get '/media_contents' => 'media_contents#find_url'

	get '/report' => 'reports#index'
	post '/report' => 'reports#create'

  get '/unavailable_time' => 'itens#unavailable_time'

end

app/models/account.rb
require 'digest/sha1'

class Account < ApplicationRecord
    ROLE_OPTIONS = %w(user admin)
    
    validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
    validates :role, presence: true, :inclusion => {:in => ROLE_OPTIONS}
    validates :password, presence: true, confirmation:true, length: { minimum: 5 }
    
    has_many :pickupaddresses
    before_create :encrypt_password
    before_create :confirmation_token
    before_validation :assign_role, on: :create
    before_validation :assign_status, on: :create
    attr_accessor :reset_token

    
    ###################### USED FOR SIGN IN ######################
    
    def self.from_omniauth(auth)
        where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |account|
            account.provider = auth.provider
            account.uid = auth.uid
            account.name = auth.info.name
            account.email = auth.info.email
            account.password = 'tempPasswordForNow'
            account.oauth_token = auth.credentials.token
            account.oauth_expires_at = Time.at(auth.credentials.expires_at)
            account.save!
        end
    end


    def encrypt_password
        if password.present?
            self.salt = 1
            
        end
    end

    
    #FIXME temporarily make all accounts "ROLE = user"
    def assign_role
        self.role = "user"
    end
    
    #Upon creation, all accounts default to have "status = created"
    def assign_status
        self.status = "created"
    end
    
    ###################### USED FOR LOGIN(AUTHENTICATION)######################
    def match_password(login_password = "")
        password == login_password
    end
    
    def authenticate(email = "", login_password = "")
        account = Account.find_by_email(email)
        
        if account && account.match_password(login_password)
            return account
            
            else
            return nil
        end
    end


    ###########################RESET PASSWORDS####################################
    def create_reset_digest
        self.reset_token = Account.new_token
        update_attribute(:reset_digest,  Account.digest(reset_token))
        update_attribute(:reset_sent_at, Time.zone.now)
    end

    #generate a random token
    def Account.new_token
        SecureRandom.urlsafe_base64
    end

    def Account.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
        BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end

    def send_password_reset_email
        AccountMailer.password_reset(self).deliver_now
    end

    def authenticated?(attribute, token)
        digest = send("#{attribute}_digest")
        return false if digest.nil?
        BCrypt::Password.new(digest).is_password?(token)
    end

    def password_reset_expired?
       reset_sent_at < 2.hours.ago
    end

    #used for email verification#
    
    def email_activate
        self.email_confirmed = true
        self.confirm_token = nil
        save!(:validate => false)
    end


    private
    def confirmation_token
        if self.confirm_token.blank?
            self.confirm_token = SecureRandom.urlsafe_base64.to_s
        end
    end
end

app/controllers/accounts_controller.rb
require 'mail'
class AccountsController < ApplicationController
    
    def create
        #render plain: params[:account].inspect
        @account = Account.new(account_params)    
        
        email = account_params[:email]
        
        profileparams = Hash.new
        profileparams[:email] = email
        username = email.split('@')
        profileparams[:display_name] = username[0]
        profileparams[:language] = "english"
        profileparams[:avatar_url] = "placeholder"  
        @profile = Profile.new(profileparams)        
        
        payparams = Hash.new
        payparams[:email] = email
        payparams[:credit] = '5'
        @pay = Pay.new(payparams)
        
        if (@account.save and @profile.save and @pay.save)
            AccountMailer.registration_confirmation(@account).deliver
            flash[:notice] = "Sign up successful!"
            redirect_to @account
        else
            render 'new'
        end
    end
    
    def show
        @account = Account.find(params[:id])
    end
    
    def edit
      @account = Account.find(params[:id])
    end
    
    def update
      @account = Account.find(params[:id])
      if @account && @account.authenticate(@account.email, account_update_params[:old_password])
          if @account.update(account_params)
              flash[:success] = 'Password Updated!'
              redirect_to edit_account_path(@account.id)
          else
              flash[:danger] = 'Failed to Update Password!'
              render 'edit'
          end
      else
          flash[:danger] = 'Wrong Original Password!'
          render 'edit'
      end
        
        
        
    end
    
    private def account_update_params
        params.require(:account).permit(:old_password, :password, :password_confirmation)
    end
    
    
    def index
    end
    
    def new
        @account = Account.new
        #render layout: false
    end
    
    private def account_params
        params.require(:account).permit(:email, :password, :password_confirmation)
    end
    
    
    def welcome_email account

        #Set the url to be the home page
        @url = '/blank'

        #Reading the email body file as erb instead of plain text or html
        email_body = ERB.new(File.read('./app/views/mail_texts/welcome_email.html.erb')).result(binding)
        
        #Compose welcome_email
        mail = Mail.new do
            from    'zeyu.feng@mail.utoronto.ca'
            to      account.email
            subject 'Welcome to Neighborrow!'
            content_type 'text/html; charset=UTF-8'
            body    email_body
        end
       
        mail.delivery_method :sendmail
        #mail.delivery_method :logger
        mail.deliver
    end

    def confirm_email
        user = Account.find_by_confirm_token(params[:id])
        if user
            user.email_activate
            flash[:success] = "Welcome to the Neighborrow! Your email has been confirmed. Please sign in to continue."
            redirect_to '/login'
            else
            flash[:error] = "Sorry. User does not exist"
            redirect_to home_path
        end
    end
    
	def userSidebar_Info
		if !current_user
			render :json => {:status => 403}
		end
		display_name = ActiveRecord::Base.connection.exec_query("SELECT display_name FROM Profiles WHERE email = '"+current_user.email+"';")
		user_id = ActiveRecord::Base.connection.exec_query("SELECT id FROM Accounts WHERE email = '"+current_user.email+"';")
		@profile = Profile.find_by_email(current_user.email)

		borrower_rate = ActiveRecord::Base.connection.exec_query("SELECT AVG(Feedback_to_borrowers.rate) AS \"borrower_avg\" FROM Requests,Feedback_to_borrowers WHERE Requests.borrower = '"+current_user.email+"' AND Requests.id = Feedback_to_borrowers.request_id;")
		#borrower_credit = ActiveRecord::Base.connection.exec_query("SELECT SUM(Feedback_to_borrowers.credit) AS \"borrower_sum\" FROM Requests,Feedback_to_borrowers WHERE Requests.borrower = '"+current_user.email+"' AND Requests.id = Feedback_to_borrowers.request_id;")
		lender_rate = ActiveRecord::Base.connection.exec_query("SELECT AVG(Feedback_to_lenders.rate) AS \"lender_avg\" FROM Requests, Itens, Feedback_to_lenders WHERE Itens.owner = '"+current_user.email+"' AND Itens.id = Requests.item_id AND Requests.id = Feedback_to_lenders.request_id;")
		#lender_credit = ActiveRecord::Base.connection.exec_query("SELECT SUM(Feedback_to_lenders.credit) AS \"lender_sum\" FROM Requests, Itens, Feedback_to_lenders WHERE Itens.owner = '"+current_user.email+"' AND Itens.id = Requests.item_id AND Requests.id = Feedback_to_lenders.request_id;")
		current_credit = Pay.where(:email => current_user.email)
		render :json => {:status => 200, :id => user_id[0]["id"], :display_name => display_name[0]["display_name"], :display_photo => url_for(@profile.avatar), :borrower_rate => borrower_rate[0]["borrower_avg"], :lender_rate => lender_rate[0]["lender_avg"], :credit => current_credit[current_credit.length-1]["credit"]}
	end

	def userDashboard_Info
		if !current_user
			render :json => {:status => 403}
		end

		display_name = ActiveRecord::Base.connection.exec_query("SELECT display_name FROM Profiles WHERE email = '"+current_user.email+"';")

		borrower_rate = ActiveRecord::Base.connection.exec_query("SELECT AVG(Feedback_to_borrowers.rate) AS \"borrower_avg\" FROM Requests,Feedback_to_borrowers WHERE Requests.borrower = '"+current_user.email+"' AND Requests.id = Feedback_to_borrowers.request_id;")
		#borrower_credit = ActiveRecord::Base.connection.exec_query("SELECT SUM(Feedback_to_borrowers.credit) AS \"borrower_sum\" FROM Requests,Feedback_to_borrowers WHERE Requests.borrower = '"+current_user.email+"' AND Requests.id = Feedback_to_borrowers.request_id;")
		lender_rate = ActiveRecord::Base.connection.exec_query("SELECT AVG(Feedback_to_lenders.rate) AS \"lender_avg\" FROM Requests, Itens, Feedback_to_lenders WHERE Itens.owner = '"+current_user.email+"' AND Itens.id = Requests.item_id AND Requests.id = Feedback_to_lenders.request_id;")
		#lender_credit = ActiveRecord::Base.connection.exec_query("SELECT SUM(Feedback_to_lenders.credit) AS \"lender_sum\" FROM Requests, Itens, Feedback_to_lenders WHERE Itens.owner = '"+current_user.email+"' AND Itens.id = Requests.item_id AND Requests.id = Feedback_to_lenders.request_id;")
		current_credit = Pay.where(:email => current_user.email)
		lended_item_list = ActiveRecord::Base.connection.exec_query("SELECT Profiles.display_name AS \"borrowerName\", Requests.time_end AS \"endDate\", Itens.name AS \"itemName\" FROM Requests, Itens, Profiles WHERE Itens.owner = '"+current_user.email+"' AND Itens.id = Requests.item_id AND Requests.borrower = Profiles.email AND Requests.status = 'accepted' AND Requests.received = 'true' AND Requests.returned = 'false';")

		borrowed_item_list = ActiveRecord::Base.connection.exec_query("SELECT Profiles.display_name AS \"lenderName\", Requests.time_end AS \"endDate\", Itens.name AS \"itemName\" FROM Requests, Itens, Profiles WHERE Requests.borrower = '"+current_user.email+"' AND Itens.id = Requests.item_id AND Itens.owner = Profiles.email AND Requests.status = 'accepted' AND Requests.received = 'true' AND Requests.returned = 'false';")
		
		pending_request_list = ActiveRecord::Base.connection.exec_query("SELECT Profiles.display_name AS \"borrowerName\", Requests.id AS \"requestID\", Requests.time_start AS \"startDate\", Requests.time_end AS \"endDate\", Itens.name AS \"itemName\" FROM Requests, Itens, Profiles WHERE Itens.owner = '"+current_user.email+"' AND Itens.id = Requests.item_id AND Requests.borrower = Profiles.email AND Requests.status = 'pending';")

		render :json => {:status => 200, :display_name => display_name[0]["display_name"], :borrower_rate => borrower_rate[0]["borrower_avg"], :credit => current_credit[current_credit.length-1]["credit"], :lender_rate => lender_rate[0]["lender_avg"], :lended_item => lended_item_list, :pending_request => pending_request_list, :borrowed_item => borrowed_item_list}
	end
	

    def resendConfirmation
        render layout: false
        @account = Account.find(params[:id])
        AccountMailer.registration_confirmation(@account).deliver
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/edit.html.erb
<!-- 
	* This modified template file is referenced to coreui.io, 
	* along with other third-party stylesheets and javascript files.
	* Source Repository: https://github.com/coreui/coreui-free-bootstrap-admin-template
-->

<!--
* CoreUI - Free Bootstrap Admin Template
* @version v2.1.7
* @link https://coreui.io
* Copyright (c) 2018 creativeLabs Łukasz Holeczek
* Licensed under MIT (https://coreui.io/license)
-->

<!DOCTYPE html>
<html lang="en">
<head>
	<!-- Meta information used for SEO -->
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
	<meta name="description" content="Neighborrow - Your Platform to Borrow and Lend">
	<meta name="author" content="Neighborrow">
	<meta name="keyword" content="Borrow, Lend, CSC444">
	<%= csrf_meta_tags %>
	<%= javascript_tag "window._token = '#{form_authenticity_token}'" %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	<title>Neighborrow - Blank</title>

	<!-- CSS files for third-party icons-->
	<link href="/vendors/@coreui/icons/css/coreui-icons.min.css" rel="stylesheet">
	<link href="/vendors/flag-icon-css/css/flag-icon.min.css" rel="stylesheet">
	<link href="/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
	<link href="/vendors/simple-line-icons/css/simple-line-icons.css" rel="stylesheet">

	<!-- Base stylesheets & third-party stylesheets-->
	<link href="/vendors/@coreui/coreui/css/style.css" rel="stylesheet">
	<link href="/vendors/pace-progress/css/pace.min.css" rel="stylesheet">

	<!-- Customized stylesheet goes here-->

</head>

<% if logged_in_as_user? (@account.id) %>
<body class="app header-fixed sidebar-fixed aside-menu-fixed sidebar-md-show" data-turbolinks="false">
	<!-- <header class="app-header navbar" style="width:100%" id="headerModule">

	</header> -->
	
	
	<div class="app-body">
		<div class="sidebar" id="menuModule"></div>

		<main class="main">
			<span id="subHeaderModule"></span>

			<div class="container-fluid">
				<!-- Main section - Codes for main functionalities in this block -->
				
				<% if flash[:success]%>
					<%= content_tag :div, flash[:success], class:"alert alert-primary" %>
					<% flash.discard %>
				<% end %>
				<% if flash[:danger]%>
					<%= content_tag :div, flash[:danger], class:"alert alert-danger"  %>
					<% flash.discard %>
				<% end %>
				
				<h2>Password Change</h2>
				<hr>
					
	            <div class="row">
	              <div class="col-lg-12">
	                <div class="card">
	                  <div class="card-header">
	                    <i class="fa fa-edit text-muted"></i>
	                    <strong class="text-muted">Password</strong>
	                  </div>
	                  <div class="card-body">
		                  <%= form_for @account, url:account_path do |f| %>
		                  	<!-- form-group// -->
	                        <div class="form-group">
		                        <label for="password">Original Password</label>
								<div class="form-group input-group">
		                            <div class="input-group-prepend">
		                                <span class="input-group-text"> <i class="fa fa-lock"></i> </span>
		                            </div>
		                            <input class="form-control" type="password" name="account[old_password]" placeholder="Your Original Password" required="required" pattern=".{8,}">
		                        </div>
	                        </div>	                        
		                  	<!-- form-group// -->
		                  	<div class="form-group">
		                        <label for="password">New Password</label>
		                        <div class="form-group input-group">
		                            <div class="input-group-prepend">
		                                <span class="input-group-text"> <i class="fa fa-lock"></i> </span>
		                            </div>
		                            <input class="form-control" type="password" name="account[password]" placeholder="Password (Minimum 8 characters)" required="required" pattern=".{8,}">
		                        </div>
	                        </div>	                        
	                        <!-- form-group// -->
		                  	<div class="form-group">
		                        <label for="password">Repeat New Password</label>
		                        <div class="form-group input-group">
		                            <div class="input-group-prepend">
		                                <span class="input-group-text"> <i class="fa fa-lock"></i> </span>
		                            </div>
		                            <input class="form-control" type="password" name="account[password_confirmation]" placeholder="Confirm Password" required="required">
		                        </div>
			                </div>
							<%= f.submit class: "btn btn--form", class: "btn btn-primary pull-right", value: "Change Password"%>
		                  <% end %>
	                  </div>
	                </div>
	              </div>
	              <!-- /.col-->
	            </div>
	            <!-- /.row-->	
			</div>
		</main>
	</div>
	
<% else %>
	<div class = "app flex-row align-items-center">
		<div class="container">
	      <div class="row justify-content-center">
	        <div class="col-md-6">
	          <div class="clearfix">
	            <h1 class="float-left display-3 mr-4">403</h1>
	            <h4 class="pt-3">Oops! Forbidden Page</h4>
	            <p class="text-muted">
		            Looks like you don't have permission to access this page.
		            You might be accessing an account that's not yours
	            </p>
	          </div>
	        </div>
	      </div>
	    </div>
	</div>
<% end %>


	<footer class="app-footer" id="footerModule"></footer>
	



<!-- CoreUI and other third-party plugins (js files) -->
    <script src="/vendors/jquery/js/jquery.min.js"></script>
    <script src="/vendors/popper.js/js/popper.min.js"></script>
    <script src="/vendors/bootstrap/js/bootstrap.min.js"></script>
    <script src="/vendors/pace-progress/js/pace.min.js"></script>
    <script src="/vendors/perfect-scrollbar/js/perfect-scrollbar.min.js"></script>
    <script src="/vendors/@coreui/coreui/js/coreui.min.js"></script>
		<script src="/vendors/momentjs/moment.js"></script>
		<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    <!-- Customized Javascript file goes here -->
    <script src="/assets/js/dashboard-init.js?version=1"></script>
    <script src="/assets/js/transaction_borrowed.js?version=1"></script>

</body>

</html>

app/views/accounts/new.html.erb
<!--
 * This modified template file is referenced to bootsnipp,
 * along with other third-party stylesheets and javascript files.
 * Source Repository: https://bootsnipp.com/snippets/z8699
 -->


<!DOCTYPE html>
<html lang="en">
    
    <head>

                <link href="/vendors/@coreui/coreui/css/style.css" rel="stylesheet">
                <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
                <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
                <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css">
                    
                    <style type="text/css">
                        .divider-text {
                            position: relative;
                            text-align: center;
                            margin-top: 15px;
                            margin-bottom: 15px;
                        }
                    .divider-text span {
                        padding: 7px;
                        font-size: 12px;
                        position: relative;
                        z-index: 2;
                    }
                    .divider-text:after {
                        content: "";
                        position: absolute;
                        width: 100%;
                        border-bottom: 1px solid #ddd;
                        top: 55%;
                        left: 0;
                        z-index: 1;
                    }
                    .btn-facebook {
                        background-color: #405D9D;
                        color: #fff;
                    }
                    .btn-google{
                        background-color: #DD4B39;
                        color: #fff;
                    }
                    </style>
    </head>
    
    <body class="app header-fixed">
        <div class="app-body flex-row align-items-center">
            <main class="main">

                
                
                <div class="align-items-center">
                    <article class="mx-auto " style="max-width: 400px;">
                        <%= form_for @account, url: accounts_path do |f| %>
                        
                        <form action="" method="post">
                            <% if @account.errors.any? %>
                            <div id="error_explanation">
                                <div class="alert alert-danger">
                                    <ul>
                                        <% @account.errors.full_messages.each do |msg| %>
                                        <li><%= msg %></li>
                                        <% end %>
                                    </ul>
                                </div>
                            </div>
                            <% end %>
                            <h3 class="card-title mt-3 text-center">Sign Up</h3>
                            <p class="text-center">Are you ready to join Neighborrow?</p>
                            <p>
                            <a href="/auth/google_oauth2" class="btn btn-block btn-google"> <i class="fab fa-google"></i>   Sign Up via Google</a>
                            <a href="/auth/facebook" class="btn btn-block btn-facebook"> <i class="fab fa-facebook-f"></i>   Sign Up via Facebook</a>
                            </p>
                            <p class="divider-text">
                            <span class="bg-light">OR</span>
                            </p>
                            
                            <form>
                                
                                <!-- form-group// -->
                                <div class="form-group input-group">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text"> <i class="fa fa-envelope"></i> </span>
                                    </div>
                                    <input class="form-control" placeholder="Email address" type="email" name="account[email]" required="required">
                                </div>
                                
                                <!-- form-group// -->
                                <div class="form-group input-group">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text"> <i class="fa fa-lock"></i> </span>
                                    </div>
                                    <input class="form-control" type="password" name="account[password]" placeholder="Password (Minimum 8 characters)" required="required" pattern=".{8,}">
                                </div>
                                
                                <!-- form-group// -->
                                <div class="form-group input-group">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text"> <i class="fa fa-lock"></i> </span>
                                    </div>
                                    <input class="form-control" type="password" name="account[password_confirmation]" placeholder="Confirm Password" required="required">
                                </div>
                                
                                <!-- form-group// -->
                                <div class="form-group text-center">
                                    <label class="checkbox-inline"><input type="checkbox" required="required"> I accept the <a href="/termsOfService" target="_blank">Terms of Service</a> &amp; <a href="/privacyPolicy" target="_blank">Privacy Policy</a></label>
                                </div>
                                
                                <!-- form-group// -->
                                <div class="form-group">
                                    <button type="submit" class="btn btn-primary btn-block"> Create Account  </button>
                                </div>
                                <%end%>
                                
                                <!-- form-group// -->
                                <p class="text-center">Have an account? <a href="/login">Log In</a> </p>
                                
                                
                            </form>
                    </article>
                </div> <!-- card.// -->
                
            </main>
        </div>
        <!--container end.//-->
        
        
    </body>
</html>

app/views/accounts/resendConfirmation.html.erb
<!--
* This modified template file is referenced to coreui.io,
* along with other third-party stylesheets and javascript files.
* Source Repository: https://github.com/coreui/coreui-free-bootstrap-admin-template
-->

<!--
* CoreUI - Free Bootstrap Admin Template
* @version v2.1.7
* @link https://coreui.io
* Copyright (c) 2018 creativeLabs Łukasz Holeczek
* Licensed under MIT (https://coreui.io/license)
-->

<!DOCTYPE html>
<html lang="en">

<head>
<!-- Meta information used for SEO -->
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
<meta name="description" content="Neighborrow - Your Platform to Borrow and Lend">
<meta name="author" content="Neighborrow">
<meta name="keyword" content="Borrow, Lend, CSC444">
<title>Neighborrow - Blank</title>

<!-- CSS files for third-party icons-->
<link href="/vendors/@coreui/icons/css/coreui-icons.min.css" rel="stylesheet">
<link href="/vendors/flag-icon-css/css/flag-icon.min.css" rel="stylesheet">
<link href="/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
<link href="/vendors/simple-line-icons/css/simple-line-icons.css" rel="stylesheet">

<!-- Base stylesheets & third-party stylesheets-->
<link href="/vendors/@coreui/coreui/css/style.css" rel="stylesheet">
<!--<link href="/vendors/pace-progress/css/pace.min.css" rel="stylesheet">-->

<!-- Customized stylesheet goes here-->
</head>


<body class="app header-fixed">
<div class="app-body flex-row align-items-center">
<main class="main">
<h1 class="text-center text-uppercase font-weight-bold">Another email has been sent!</h1>
<div class = "col-md-6 offset-md-3">
<p>Please check your junk mailbox as well. If you still don't receive an email, please contact our technical support at <a href="mailto:sixneighborrow@gmail.com">sixneighborrow@gmail.com </a>.</p>
</div>
</main>
</div>
</body>
</html>